// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOb4lHP_PDnjb08vQp0jXOeAomBka3Jrc',
    appId: '1:204248408447:web:f3cfe4610c76af43087a4a',
    messagingSenderId: '204248408447',
    projectId: 'rudra-and-research',
    authDomain: 'rudra-and-research.firebaseapp.com',
    storageBucket: 'rudra-and-research.firebasestorage.app',
    measurementId: 'G-1DGG063KWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOqyKFSoKTltHhPtXoLs_G_Cz2DEBlbI',
    appId: '1:204248408447:android:95ef8d09cdb08c70087a4a',
    messagingSenderId: '204248408447',
    projectId: 'rudra-and-research',
    storageBucket: 'rudra-and-research.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_EX1Ko-BpOrcsIh4osgPB_yQwmCvM9A',
    appId: '1:204248408447:ios:16cfe6857204f5db087a4a',
    messagingSenderId: '204248408447',
    projectId: 'rudra-and-research',
    storageBucket: 'rudra-and-research.firebasestorage.app',
    iosBundleId: 'com.quick.rudra.rudra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7_EX1Ko-BpOrcsIh4osgPB_yQwmCvM9A',
    appId: '1:204248408447:ios:16cfe6857204f5db087a4a',
    messagingSenderId: '204248408447',
    projectId: 'rudra-and-research',
    storageBucket: 'rudra-and-research.firebasestorage.app',
    iosBundleId: 'com.quick.rudra.rudra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOb4lHP_PDnjb08vQp0jXOeAomBka3Jrc',
    appId: '1:204248408447:web:79efd0130fef65ac087a4a',
    messagingSenderId: '204248408447',
    projectId: 'rudra-and-research',
    authDomain: 'rudra-and-research.firebaseapp.com',
    storageBucket: 'rudra-and-research.firebasestorage.app',
    measurementId: 'G-NDH0T54HLH',
  );
}
